### ISSUE TITLE
time unit mistake.

### ISSUE THREAD

**Issue by simpzan** [ot/path_decomposed_tries#1]
in src file `perftest/perftest_common.hpp` line 17, the time returned by `boost::posix_time::microsec_clock::universal_time()` is in ms unit, not in us unit.

**Comment by ot** [comment]
I'm not sure I understand your point, if you check out line 17 we call total_microseconds() on the time delta, so the result is in us.

```
double elapsed_usec = static_cast<double>((boost::posix_time::microsec_clock::universal_time() - m_tick).total_microseconds());
```

**Comment by simpzan** [comment]
Oh, sorry, I made the mistake.
